FROM golang:1.25.1@sha256:d7098379b7da665ab25b99795465ec320b1ca9d4addb9f77409c4827dc904211 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./gen-key ./cmd/gen-key

FROM golang:1.25.1@sha256:d7098379b7da665ab25b99795465ec320b1ca9d4addb9f77409c4827dc904211 

WORKDIR /home/app

COPY --from=build /build/gen-key ./

ENTRYPOINT ["./gen-key"]
CMD ["--origin=binarytransparency.log/example", "--private-key-path=/home/app/keys/private.key", "--public-key-path=/home/app/keys/public.key"]
