FROM golang:1.25.1@sha256:d7098379b7da665ab25b99795465ec320b1ca9d4addb9f77409c4827dc904211 AS build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 go build -v -o ./witness-add-key ./cmd/witness-add-key

FROM golang:1.25.1@sha256:d7098379b7da665ab25b99795465ec320b1ca9d4addb9f77409c4827dc904211

WORKDIR /home/app

RUN apt-get update
RUN apt-get install sqlite3

RUN mkdir witness
RUN sqlite3 -line witness/witness.db '.database'

COPY --from=build /build/witness-add-key ./

ENTRYPOINT ["./witness-add-key"]
CMD ["--database-path=/home/app/witness/witness.db", "--public-key=/home/app/keys/public.key"]
